version: '3'

services:
  dns:
    image: sameersbn/bind:latest
    container_name: dns_server
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    environment:
      - ROOT_PASSWORD=Prueba-123
      - DNS_FORWARDER=8.8.8.8
    volumes:
      - ./conf:/etc/bind
      - ./zonas:/var/lib/bind
